<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ModuleFastCore</AssemblyName>
    <RootNamespace>ModuleFast</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management.Automation" PrivateAssets="all" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="Polly.Core" />
  </ItemGroup>
</Project>
